-- ACT 4: HOW HEALTHY IS THAT REVENUE?
-- Refund rates, refund reasons, discount analysis,
-- gross vs net revenue comparison.

-- REFUND ANALYSIS
-- Overall refund rate
WITH refund AS (
    SELECT
        SUM(CASE WHEN is_refunded = TRUE  THEN 1 END) AS refunded,
        SUM(CASE WHEN is_refunded = FALSE THEN 1 END) AS not_refunded,
        COUNT(*) AS total_orders
    FROM events
)
SELECT
    refunded,
    not_refunded,
    total_orders,
    ROUND(refunded * 100.00 / total_orders, 2) AS refund_rate_pct
FROM refund;
-- 1,005 orders are refunded out of ~48,000 total orders which is ~2.1%
-- This is considered low overall, but can subscriptions get refunded?

-- Confirm subscriptions can be refunded
SELECT
    p.product_name,
    p.vendor,
    p.billing_cycle,
    COUNT(*) AS total_refunds
FROM events e
JOIN products p ON e.product_id = p.product_id
WHERE e.is_refunded = TRUE
GROUP BY product_name, p.vendor, p.billing_cycle
ORDER BY total_refunds DESC; --Yes, subscriptions can be refunded, 
-- but they are a small fraction of total refunds (only 3 subscription refunds out of 1,005 total refunds)


-- Refund reasons
SELECT
    refund_reason,
    COUNT(*) AS total_refunds
FROM events
WHERE is_refunded = TRUE
GROUP BY refund_reason
ORDER BY total_refunds DESC;
-- Billing errors and accidental purchases are the top causes of refunds
-- Service dissatisfaction is the least common reason
-- The refund reasons are mostly operational failures, and not product failures,
-- this is fixable without changing the product catalogue


-- True refund rate by category
-- (refunds as % of that category's own orders)
SELECT
    p.category,
    COUNT(*) AS total_orders,
    SUM(CASE WHEN e.is_refunded = TRUE THEN 1 ELSE 0 END) AS total_refunds,
    ROUND(SUM(CASE WHEN e.is_refunded = TRUE THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS refund_rate_pct
FROM events e
JOIN products p ON e.product_id = p.product_id
GROUP BY p.category
ORDER BY refund_rate_pct DESC;
-- Project Management has the highest rate at ~2.3%
-- The design category warrants closer investigation


-- True refund rate by country
SELECT
    country,
    COUNT(*) AS total_orders,
    SUM(CASE WHEN is_refunded = TRUE THEN 1 ELSE 0 END) AS total_refunds,
    ROUND(SUM(CASE WHEN is_refunded = TRUE THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS refund_rate_pct
FROM events
GROUP BY country
ORDER BY refund_rate_pct DESC; -- Brazil has the highest rate (~2.5%), Philippines the lowest (~1.7%)


-- True refund rate by channel
SELECT
    channel,
    COUNT(*) AS total_orders,
    SUM(CASE WHEN is_refunded = TRUE THEN 1 ELSE 0 END) AS total_refunds,
    ROUND(SUM(CASE WHEN is_refunded = TRUE THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS refund_rate_pct
FROM events
GROUP BY channel
ORDER BY refund_rate_pct DESC; -- Marketplace is highest (~2.4%), Website second (~2.1%)



-- DISCOUNT ANALYSIS
-- Overall discount impact
SELECT
    SUM(discount_local * fx_rate_to_usd) AS total_discount_usd,
    SUM(net_revenue_usd) AS total_revenue,
    ROUND(SUM(discount_local * fx_rate_to_usd) * 100.0 / SUM(net_revenue_usd), 2) AS discount_pct
FROM events; -- ~4% of total revenue goes to discounts, this is within a healthy range


-- Discount cost and revenue generated by channel
SELECT
    channel,
    SUM(discount_local * fx_rate_to_usd) AS total_discount_cost,
    SUM(net_revenue_usd) AS total_revenue,
    ROUND(SUM(discount_local * fx_rate_to_usd) * 100.0 / SUM(net_revenue_usd), 2) AS discount_pct
FROM events
GROUP BY channel;
-- Partner channel has highest discount % (~4.3%)
-- Website spends most on discounts (~$559K) but generates, ~$4.7M in revenue from discounted orders

-- Revenue generated specifically from discounted orders by channel
SELECT
    channel,
    SUM(discount_local * fx_rate_to_usd) AS total_discount_cost,
    SUM(CASE WHEN discount_local * fx_rate_to_usd > 0 THEN net_revenue_usd END) AS revenue_from_discounted_orders,
    ROUND(SUM(discount_local * fx_rate_to_usd) * 100.0 / SUM(net_revenue_usd), 2) AS discount_pct
FROM events
GROUP BY channel;


-- Discount code performance - cost and savings per use
SELECT
    discount_code,
    SUM(discount_local * fx_rate_to_usd) AS total_discount_usd,
    COUNT(*) AS times_used,
    ROUND(SUM(discount_local * fx_rate_to_usd) / COUNT(*), 2) AS discount_per_use
FROM events
WHERE discount_code IS NOT NULL
GROUP BY discount_code
ORDER BY discount_per_use DESC;
-- BFCM20 is the discount code with the highest per-use savings ($125/use, $332K total)
-- WELCOME10 is the most frequently used discount code (2,730 times)
-- Total customer savings: ~$1.26M (~4% of revenue)


-- Discount code performance, revenue generated
SELECT
    discount_code,
    SUM(discount_local * fx_rate_to_usd) AS total_discount_usd,
    COUNT(*) AS times_used,
    SUM(CASE WHEN discount_local * fx_rate_to_usd > 0 THEN net_revenue_usd END) AS revenue_from_discount,
    ROUND(SUM(CASE WHEN discount_local * fx_rate_to_usd > 0 THEN net_revenue_usd END) / COUNT(*), 2) AS revenue_per_use
FROM events
WHERE discount_code IS NOT NULL
GROUP BY discount_code
ORDER BY revenue_from_discount DESC;
-- NEWCUSTOMER10 generates the most revenue from discounted orders at ~$1.77M across 2,700 uses,
-- a new customer acquisition code quietly driving top revenue


-- Gross vs net revenue
SELECT
    SUM((net_revenue_local + discount_local) * fx_rate_to_usd) AS gross_rev_usd,
    SUM(net_revenue_usd) AS net_rev_usd,
    SUM(discount_local * fx_rate_to_usd) AS total_discounts_usd
FROM events;
-- Net revenue is close to the gross revenue, the money left on discounts are not excessive
-- Just enough is given away for customers to save and return
